export const LOGIN = "LOGIN";
export const GETALLCOMPANIES = "GETALLCOMPANIES";
export const SEARCHCOMPANIES = "SEARCHCOMPANIES";
export const GETALLSTUDENTJOBS = "GETALLSTUDENTJOBS";
export const FILTERJOBS = "FILTERJOBS";
export const SEARCHJOBS = "SEARCHJOBS";
export const SEARCHINTERVIEWS = "SEARCHINTERVIEWS"